version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped

  # Service supplémentaire : Redis pour le cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 